FROM openjdk:17-oracle
ARG JAR_FILE=build/libs/Mukvengers-1.0.0.jar
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL} \
SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME} \
SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD} \
JWT_ISSUER=${JWT_ISSUER} \
JWT_SECRET_KEY=${JWT_SECRET_KEY} \
AWS_ACCESS_KEY=${AWS_ACCESS_KEY} \
AWS_SECRET_KEY=${AWS_SECRET_KEY} \
SERVER_ADDRESS=${SERVER_ADDRESS} \
CLIENT_ID=${CLIENT_ID} \
CLIENT_SECRET=${CLIENT_SECRET} \
REDIRECT_URI=${REDIRECT_URI} \
KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID} \
KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET} \
KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI} \
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} \
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]