FROM openjdk:17-oracle
ARG JAR_FILE=build/libs/*.jar
ENV SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL} \
SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME} \
SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD} \
JWT_ISSUER=${JWT_ISSUER} \
JWT_SECRET_KEY=${JWT_SECRET_KEY} \
AWS_ACCESS_KEY=${AWS_ACCESS_KEY} \
AWS_SECRET_KEY=${AWS_SECRET_KEY}
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]